spring:
  application:
    name: KaAPI
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/KaAPI
    username: root
    password: 196851444
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session
  session:
    timeout: 86400
    store-type: redis
  # redis
  redis:
    port: 6379
    host: localhost
    database: 0
server:
  port: 7529
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0


kaapi:
  client:
    access-key: kaka
    secret-key: 123456

dubbo:
  application:
    name: KaAPI-backend-provider
  protocol:
    name: dubbo
    port: 22221
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
